backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: "music"
    label: "Music"
    folder: "src/pages/music/"
    create: true
    fields:
      - { name: "type", label: "Type", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "buy", label: "Buy Link", widget: "string", required: false }
      - { name: "spotify", label: "Spotify", widget: "string" }
      - { name: "apple", label: "Apple", widget: "string" }
      - { name: "cover", label: "Cover", widget: "image" }
  - name: "tabs"
    label: "Tabs"
    folder: "src/pages/tabs/"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "cta", label: "CTA", widget: "string" }
      - { name: "type", label: "Type", widget: "select" , options: ["All", "Tool","Game Of Thrones", "Original", "Other"] }
